baseURL = 'https://dropmorepackets.github.io/'
languageCode = 'en-us'
title = 'Drop More Packets - Knowledgebase'
enableGitInfo = true
disableKinds = ['taxonomy', 'taxonomyTerm']

[module]
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'

[params]
  BookToC = true
  BookMenuBundle = '/menu'
  BookRepo = 'https://github.com/DropMorePackets/dropmorepackets.github.io'
  BookCommitPath = 'commit'
  BookEditPath = 'edit/master'
  BookDateFormat = 'Jan 2, 2006'
  BookComments = false
